Add Dolly as the Input Model
databrickslabs/dolly pull request #164
Opened 2023-05-14 22:53 UTC by xuanyuanking

Combine it with https://github.com/databrickslabs/dolly/pull/163. With the ability to train the model using local files, we can now include Dolly v2 models as an option in the suggested input models.

In our test scenario, we observed that fine-tuning based on Dolly yielded better performance compared to fine-tuning based on the base models directly.

2023-05-15 14:25 UTC, srowen requested changes
Adding the options part is fine

2023-05-15 14:25 UTC, srowen commented on README.md
> +- You can also directly use Dolly as the input model and further train your own model using your file tuning records uploaded to the data directory. Simply upload the files and set `local_files` as t
Revert this change

2023-05-16 15:28 UTC, srowen approved these changes

2023-05-16 15:29 UTC, srowen requested changes

2023-05-16 17:48 UTC, xuanyuanking commented on training/consts.py
> +    "databricks/dolly-v2-3b"
ah yea, fix done!

2023-05-16 18:29 UTC, srowen approved these changes

2023-05-16 18:29 UTC, merged