add generate example and simple shell command to execute the training
databrickslabs/dolly pull request #19
Opened 2023-03-27 14:07 UTC by youkaichao

This PR addresses the issue https://github.com/databrickslabs/dolly/issues/8

2023-03-27 20:14 UTC, srowen commented
I don't think this belongs in a README - maybe just a separate .sh file in the repo? but I am also not clear if we want to duplicate the training code. .py code seems like the more natural delivery mechanism. Granted, it has shell commands in it, but Jupyter, Databricks et al can understand those. If anything I would like to just migrate the notebook to .ipynb

2023-03-27 22:39 UTC, youkaichao commented
@srowen Hey, I can move the code into a separate .sh if you like. The problem this PR wants to resolve is that many people want to try Dolly without databricks environment, and a separate .sh would be super useful :)

2023-03-27 23:03 UTC, srowen commented
I personally think the generate example is a good idea, but not a second copy of the training code, which seems more natural in Python. Databricks is not required, already.

2023-03-27 23:05 UTC, srowen requested changes
I'm not able to merge but i think these would be useful changes

2023-03-27 23:05 UTC, srowen commented on generate.py
> +from transformers import AutoModelForCausalLM, AutoTokenizer
Add space and copyright header

2023-03-27 23:05 UTC, srowen commented on generate.py
> +model_name = path
this is redundant

2023-03-27 23:05 UTC, srowen commented on generate.py
> +model.to(device)
just `model.to("cuda:0")` and inline it above

2023-03-27 23:05 UTC, srowen commented on generate.py
> +            max_length=300,  # Controls the maximum length of the generated text
Can we make these parameters that you can pass on the command line, so you can run with `python`?

2023-03-28 00:57 UTC, youkaichao commented
I personally think the `train_dolly.py` is too long, and thus simplify it into several shell commands.

2023-03-28 01:42 UTC, srowen commented
That's an advantage to being in a notebook, it's broken up naturally. I think you can maintain your own port as you like in a fork. The generate script sounds interesting though, that seems important to have.

2023-03-28 02:04 UTC, youkaichao commented
Okay, then I will only keep the generate example.

2023-03-28 02:34 UTC, youkaichao commented
By the way, the generate script is what I get from ChatGPT. Therefore, many hyper-parameters are not tuned :)

2023-03-28 03:49 UTC, srowen commented
Oh I think @matthayes is going to add a generation script like what was used for the blog, to reproduce the result. That may already be coming

2023-03-28 05:12 UTC, matthayes commented
Yes I just opened #27 for this.  Sorry for being late to post the generation code.

2023-03-28 06:08 UTC, closed without merging